name: 'update'

on:
  workflow_dispatch:
  repository_dispatch:
    # https://github.com/apps/octokit-release-notifier
    types: [octokit/webhooks release]

env:
  # reduces noise from npm post-install scripts
  DISABLE_OPENCOLLECTIVE: true
  OPEN_SOURCE_CONTRIBUTOR: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm install -ED @octokit/webhooks-schemas@latest @octokit/webhooks-types@latest
      - run: rm -rf src/schemas
      - run: npm run --silent copy-schemas
      - run: npm run --silent generate-types
      - name: create pull request
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          title: "\U0001F6A7 \U0001F916\U0001F4EF Webhooks changed"
          body: >
            A new release of
            [@octokit/webhooks](https://github.com/octokit/webhooks) was just
            released!

            This PR updates that package, along with copying the schemas &
            regenerating the types that are derived from `@octokit/webhooks`.
          branch: 'update-octokit-webhooks'
          author: 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>'
          commit-message: 'feat: update `@octokit/webhooks-definitions`'
      - name: trigger ci checks
        uses: octokit/request-action@v2.x
        with:
          route: |
            POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          workflow_id: checks.yaml
          ref: update-octokit-webhooks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
